# Assignments for Unit 4 - Projects {#sec-assignment4}

::: {.callout-note appearance="simple"}
This includes the list of assignments for Unit 4 associated with Projects.
:::

```{r}
#| label: tbl-unit4assignments
#| tbl-cap: Assignments from Unit 4
#| echo: false
#| warning: false
library(dplyr)
library(kableExtra)

assignment <- c('Haley et al., Historical Redlining and Present Air Pollution in US Cities')
due.Date <- c('Oct 21, 2022')
source <- c('https://pubs.acs.org/doi/pdf/10.1021/acs.estlett.1c01012')

unit4 <- data.frame(assignment, due.Date, source)# %>% 

unit4 %>% mutate(link = cell_spec(row.names(.), 'html', link = source)) %>% 
  select(-source) %>% 
  kableExtra::kable('html', escape = FALSE) %>% 
  kable_material_dark(c('condensed', 'hover')) %>% 
  column_spec(1, width = '20em') #%>

```

## Group Presentation 

Teams of approximately 4 students (3-5 allowed). End product is a 12 minute presentation in class using slides and data visualizations.  

It should include approximately:

- 3 minutes of introduction and background
- 3 minutes defining the scope of your Project
  * Spatial extent (e.g., state of California)
  * Temporal extent (i.e., year-range)
  * Environmental variable(s) to be examined (air pollution, water, radiation, climate, etc.)
- 3 minutes on what the team's hypothesis is and what data will be acquired for exploring that hypothesis.
- 3 minutes on the visualization strategies that will help tell the story. What will the project look like (hand-drawn sketches or design mock-ups are fine).  

### Grading for Group Presentation Project

Total of 200 points.  

* 50 points from other group members (participation grade - anonymous)
* 75 points for quality of presentation slides
  - 15 points for spelling/grammar/formatting
  - 40 points for content, text, and visualizations
  - 20 points for covering 4 topic areas
* 75 points for presentation 
  - 25 points for covering 4 topic areas
  - 20 points for having approximately equal talking time among team members
  - 30 points for content mastery and for answering questions from classmates and Professor Mike